
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO = 11;
  public static final int DOSPUNTOS = 9;
  public static final int INT = 10;
  public static final int BARRA_V = 21;
  public static final int FLECHA = 6;
  public static final int RSALTOLINEA = 13;
  public static final int RCOMILLAS = 16;
  public static final int ID = 17;
  public static final int POR = 5;
  public static final int CARACTER = 20;
  public static final int STRING = 19;
  public static final int COMA = 14;
  public static final int EOF = 0;
  public static final int RCOMILLAD = 15;
  public static final int CONJ = 12;
  public static final int PAR_IZQ = 2;
  public static final int CULEBRA = 18;
  public static final int error = 1;
  public static final int PAR_DER = 3;
  public static final int LLAVE_IZQ = 7;
  public static final int PUNTOCOMA = 22;
  public static final int LLAVE_DER = 8;
  public static final int MAS = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAR_IZQ",
  "PAR_DER",
  "MAS",
  "POR",
  "FLECHA",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "DOSPUNTOS",
  "INT",
  "PUNTO",
  "CONJ",
  "RSALTOLINEA",
  "COMA",
  "RCOMILLAD",
  "RCOMILLAS",
  "ID",
  "CULEBRA",
  "STRING",
  "CARACTER",
  "BARRA_V",
  "PUNTOCOMA"
  };
}

