
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_DER = 5;
  public static final int DISTINTO = 20;
  public static final int RIMPRIMIR = 36;
  public static final int RSTRING = 29;
  public static final int RTRUE = 34;
  public static final int POR = 13;
  public static final int TCHAR = 8;
  public static final int INT = 27;
  public static final int PUNTOCOMA = 28;
  public static final int COR_DER = 3;
  public static final int RFALSE = 35;
  public static final int NOT = 23;
  public static final int MENORIGUAL = 18;
  public static final int AND = 21;
  public static final int IGUAL = 6;
  public static final int OR = 22;
  public static final int RDOUBLE = 30;
  public static final int DIV = 14;
  public static final int ID = 24;
  public static final int MAYORIGUAL = 17;
  public static final int EOF = 0;
  public static final int DECIMAL = 26;
  public static final int error = 1;
  public static final int COMA = 7;
  public static final int MODULO = 10;
  public static final int MENOS = 12;
  public static final int MENOR = 16;
  public static final int PAR_IZQ = 4;
  public static final int RCHAR = 32;
  public static final int MAYOR = 15;
  public static final int POTENCIA = 9;
  public static final int COR_IZQ = 2;
  public static final int STRING = 25;
  public static final int RINT = 31;
  public static final int RBOOL = 33;
  public static final int EQUIVALENTE = 19;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COR_IZQ",
  "COR_DER",
  "PAR_IZQ",
  "PAR_DER",
  "IGUAL",
  "COMA",
  "TCHAR",
  "POTENCIA",
  "MODULO",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MAYOR",
  "MENOR",
  "MAYORIGUAL",
  "MENORIGUAL",
  "EQUIVALENTE",
  "DISTINTO",
  "AND",
  "OR",
  "NOT",
  "ID",
  "STRING",
  "DECIMAL",
  "INT",
  "PUNTOCOMA",
  "RSTRING",
  "RDOUBLE",
  "RINT",
  "RCHAR",
  "RBOOL",
  "RTRUE",
  "RFALSE",
  "RIMPRIMIR"
  };
}

